--- 
abstract: a profiler printing at once instead of recording queries.
author: 
  - Makamaka Hannyaharamitu, <makamaka[at]cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Skinny-Profiler-ProfileLogger
no_index: 
  directory: 
    - inc
    - t
requires: 
  DBIx::Skinny: 0
tests: t/*.t
version: 0.01
